# Generated by Django 6.0.3 on 2026-03-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('closed', 'Encerrado')], default='active', max_length=10, verbose_name='Status')),
                ('company_size', models.CharField(choices=[('S', 'Pequeno'), ('M', 'Médio'), ('L', 'Grande')], max_length=1, verbose_name='Porte na Contratação')),
                ('survey_frequency_days', models.IntegerField(verbose_name='Frequência de Pesquisa (dias)')),
                ('last_survey_date', models.DateField(blank=True, null=True, verbose_name='Data da Última Pesquisa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_services', to='contracts.contract', verbose_name='Contrato')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_services', to='organizations.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Serviço do Contrato',
                'verbose_name_plural': 'Serviços do Contrato',
                'unique_together': {('contract', 'service')},
            },
        ),
    ]
