# Generated by Django 6.0.3 on 2026-03-25 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do Contato')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('size', models.CharField(choices=[('S', 'Pequeno'), ('M', 'Médio'), ('L', 'Grande')], max_length=1, verbose_name='Porte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='organizations.filial', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Data de Contratação')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Serviço do Cliente',
                'verbose_name_plural': 'Serviços do Cliente',
                'unique_together': {('client', 'service')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='services',
            field=models.ManyToManyField(related_name='clients', through='clients.ClientService', to='organizations.service', verbose_name='Serviços Contratados'),
        ),
    ]
