# Generated by Django 6.0.3 on 2026-03-25 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Data Agendada')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluída'), ('O', 'Atrasada')], default='P', max_length=1, verbose_name='Status')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_survey', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pesquisa Agendada',
                'verbose_name_plural': 'Pesquisas Agendadas',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
