# Generated by Django 6.0.3 on 2026-03-25 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledsurvey',
            name='last_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_schedule', to='surveys.survey', verbose_name='Última Pesquisa'),
        ),
    ]
