# Generated by Django 6.0.3 on 2026-03-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('contracts', '0001_initial'),
        ('schedule', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledsurvey',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_survey_contract', to='contracts.contract', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='scheduledsurvey',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_survey', to='clients.client', verbose_name='Cliente'),
        ),
    ]
