# Generated by Django 6.0.3 on 2026-03-25 18:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_conducted', models.DateField(verbose_name='Data da Pesquisa')),
                ('respondent_name', models.CharField(max_length=200, verbose_name='Nome do Respondente')),
                ('respondent_role', models.CharField(max_length=200, verbose_name='Cargo do Respondente')),
                ('nps_score', models.IntegerField(help_text='De 0 a 10, o cliente indicaria a empresa?', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota Geral (NPS)')),
                ('comments', models.TextField(blank=True, verbose_name='Comentários')),
                ('is_historical', models.BooleanField(default=False, help_text='Marque se esta pesquisa foi realizada antes do sistema existir.', verbose_name='Pesquisa Histórica')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='clients.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys_created', to=settings.AUTH_USER_MODEL, verbose_name='Pesquisador')),
            ],
            options={
                'verbose_name': 'Pesquisa',
                'verbose_name_plural': 'Pesquisas',
                'ordering': ['-date_conducted'],
            },
        ),
        migrations.CreateModel(
            name='ServiceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.service', verbose_name='Serviço')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_scores', to='surveys.survey', verbose_name='Pesquisa')),
            ],
            options={
                'verbose_name': 'Nota por Serviço',
                'verbose_name_plural': 'Notas por Serviço',
                'unique_together': {('survey', 'service')},
            },
        ),
    ]
