# Generated by Django 6.0.3 on 2026-03-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Improvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Ponto a Melhorar',
                'verbose_name_plural': 'Pontos a Melhorar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Ponto Forte',
                'verbose_name_plural': 'Pontos Fortes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='improvements',
            field=models.ManyToManyField(blank=True, to='surveys.improvement', verbose_name='Pontos a Melhorar'),
        ),
        migrations.AddField(
            model_name='survey',
            name='strengths',
            field=models.ManyToManyField(blank=True, to='surveys.strength', verbose_name='Pontos Fortes'),
        ),
    ]
