# Generated by Django 6.0.3 on 2026-03-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('surveys', '0002_improvement_strength_survey_improvements_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('client', 'date_conducted')},
        ),
    ]
