# Generated by Django 6.0.3 on 2026-03-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('contracts', '0001_initial'),
        ('surveys', '0003_alter_survey_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='contracts.contract', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='clients.client', verbose_name='Cliente'),
        ),
    ]
